import type { ManifestOptions } from "vite-plugin-pwa";

export const pwaManifest: ManifestOptions = {
  name: "Mir Portofolio",
  short_name: "ViteReact",
  start_url: ".",
  display: "standalone",
  background_color: "#ffffff",
  theme_color: "#3b82f6",
  icons: [
    {
      src: "pwa-192x192.png",
      sizes: "192x192",
      type: "image/png",
    },
    {
      src: "pwa-512x512.png",
      sizes: "512x512",
      type: "image/png",
    },
    {
      src: "pwa-512x512.png",
      sizes: "512x512",
      type: "image/png",
      purpose: "any maskable",
    },
  ],
  description: "",
  file_handlers: [],
  scope: "",
  id: "",
  orientation: "any",
  display_override: [],
  dir: "ltr",
  lang: "",
  publicPath: "",
  related_applications: [],
  prefer_related_applications: false,
  protocol_handlers: [],
  shortcuts: [],
  screenshots: [],
  categories: [],
  iarc_rating_id: "",
  share_target: {
    action: "",
    method: undefined,
    enctype: undefined,
    params: {
      title: undefined,
      text: undefined,
      url: undefined,
      files: undefined,
    },
  },
  scope_extensions: [],
};
